# /backstage-templates/atlas-cluster/skeleton/atlas-deployment-skeleton.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: my-atlas-cluster
  # namespace: mongodb-atlas-operator # Or make this a parameter
  labels:
    environment: ${{ values.environment }}
    # owner: ${{ user.entity.metadata.name }}
spec:
  projectName: paulcheong-project-k8s 
  deploymentSpec:
    name: ${{ values.clusterNameInAtlas }}
    providerSettings:
      instanceSizeName: ${{ values.instanceSizeName }} # e.g., M10, M20
      providerName: ${{ values.providerName }} # e.g., AWS, GCP, AZURE
      regionName: ${{ values.regionName }}
  # Add other necessary spec fields like backup, BI connector, etc.