# /backstage-templates/atlas-cluster/skeleton/atlas-deployment-skeleton.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: ${{ values.clusterNameInAtlas }}-deployment
  # namespace: mongodb-atlas-operator # Or make this a parameter
  labels:
    environment: ${{ values.environment }}
    # owner: ${{ user.entity.metadata.name }}
spec:
  projectRef: 
    name: paulcheong-project-k8s 
  deploymentSpec:
    clusterType: REPLICASET
    tags:
      - key: "environment"
        value: ${{ values.environment }}
    name: ${{ values.clusterNameInAtlas }}
    replicationSpecs:
      - zoneName: US-Zone
        regionConfigs:
          - electableSpecs:
              intanceSize: ${{ values.instanceSizeName }}
              nodeCount: 3
              providerName: ${{ values.providerName }}
              regionName: ${{ values.regionName }}
              priority: 7
