# /backstage-templates/atlas-cluster-skeleton/catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: -config # Templated
  description: Atlas cluster configuration for backstage # Templated
  annotations:
    github.com/project-slug: positive-mental-attitude/-config # Templated
spec:
  type: service-configuration
  lifecycle: development # Templated
  # owner:  # Removed owner