apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-resources
  namespace: argocd 
  labels:
    environment: development
spec:
  project: default
  source:
    repoURL: 'https://github.com/positive-mental-attitude/templates-repo.git'
    path: 'atlas-crds' 
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: 'default' 
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true 