apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: my-project
  labels:
    environment: staging
spec:
  name: Test Atlas Operator Project
  projectIpAccessList:
    - ipAddress: 34.124.213.123
      comment: "Adding IP to Atlas access list"