# /backstage-templates/atlas-cluster/skeleton/atlas-deployment-skeleton.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: my-atlas-cluster
  namespace: mongodb-atlas-operator # Or make this a parameter
  labels:
    environment: development
    # owner: 
spec:
  projectName: paulcheong-project-k8s # Assumes project already exists
  deploymentSpec:
    name: backstage
    providerSettings:
      instanceSizeName: M10 # e.g., M10, M20
      providerName: AWS # e.g., AWS, GCP, AZURE
      regionName: US_EAST_1
  # Add other necessary spec fields like backup, BI connector, etc.