# /backstage-templates/atlas-cluster/skeleton/atlas-deployment-skeleton.yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: test-app-deployment
  # namespace: mongodb-atlas-operator # Or make this a parameter
  labels:
    environment: development
    # owner: 
spec:
  projectRef: 
    name: paulcheong-project-k8s 
  deploymentSpec:
    clusterType: REPLICASET
    tags:
      - key: "environment"
        value: development
    name: test-app
    replicationSpecs:
      - zoneName: US-Zone
        regionConfigs:
          - electableSpecs:
              intanceSize: M10
              nodeCount: 3
              providerName: AWS
              regionName: US_EAST_1
              priority: 7
