# /backstage-templates/create-atlas-cluster/template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-mongodb-atlas-cluster
  title: Create MongoDB Atlas Cluster
  description: Provisions a new MongoDB Atlas cluster by creating a new config repo and a PR to the main ArgoCD repo.
spec:
  owner: platform-team@example.com
  type: service
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName # This will be used for K8s CR name and new repo suffix
        - atlasProjectNameK8s
        - clusterNameInAtlas
        - environment
        - providerName
        - regionName
        - instanceSizeName
      properties:
        clusterName:
          title: Cluster Identifier (for K8s CR & New Repo)
          type: string
          description: Unique identifier for the cluster (e.g., my-app-user-db). Used for K8s CR name and new repo suffix.
          pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' # Example: lowercase alphanumeric with hyphens
        atlasProjectNameK8s:
          title: Target AtlasProject Kubernetes Name
          type: string
          description: The 'metadata.name' of the AtlasProject CR to deploy this cluster into (e.g., my-atlas-project-k8s).
        clusterNameInAtlas:
          title: Cluster Name in Atlas UI
          type: string
          description: The name that will appear for this cluster in the MongoDB Atlas UI.
        environment:
          title: Environment
          type: string
          default: development
          enum:
            - development
            - staging
            - production
        providerName:
          title: Cloud Provider
          type: string
          enum: [AWS, GCP, AZURE]
          default: GCP
        regionName:
          title: Region
          type: string
          default: US_EAST_1
        instanceSizeName:
          title: Instance Size
          type: string
          default: M10

  steps:
    - id: fetch-and-template-crd
      name: Fetch Skeleton and Template CRD
      action: fetch:template
      input:
        url: ../atlas-deployment-skeleton.yaml # Path to the skeleton file, relative to this template.yaml
        # Place the templated file into a 'content' subdirectory in the workspace
        targetPath: content/${{ parameters.clusterName }}-deployment.yaml
        values:
          clusterName: ${{ parameters.clusterName }} # This will be the metadata.name of the AtlasDeployment CR
          atlasProjectNameK8s: ${{ parameters.atlasProjectNameK8s }}
          clusterNameInAtlas: ${{ parameters.clusterNameInAtlas }}
          environment: ${{ parameters.environment }}
          providerName: ${{ parameters.providerName }}
          regionName: ${{ parameters.regionName }}
          instanceSizeName: ${{ parameters.instanceSizeName }}
          user: ${{ user }}

    - id: publish-new-config-repo
      name: Create New GitHub Repo for Cluster Config
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'Configuration repository for Atlas cluster: ${{ parameters.clusterNameInAtlas }}'
        repoUrl: 'https://github.com/positive-mental-attitude/${{ parameters.clusterName }}-config.git'
        commitMessage: 'Initial commit: AtlasDeployment CRD for ${{ parameters.clusterNameInAtlas }}'
        # sourcePath should point to the directory containing the file(s) to be committed to the new repo's root
        sourcePath: content # This will commit the content of the 'content' directory (i.e., your CRD file)
                            # to the root of the new repository.

    - id: create-pr-to-argocd-repo
      name: Create Pull Request to ArgoCD Watched Repo
      action: publish:github:pull-request
      input:
        repoUrl: 'https://github.com/positive-mental-attitude/templates-repo.git'
        branchName: feat/add-cluster-${{ parameters.clusterName }}
        title: 'feat: Request to add Atlas cluster - ${{ parameters.clusterNameInAtlas }}'
        description: |
          Please review and merge this Pull Request to add the AtlasDeployment CRD for cluster:
          - Kubernetes CR Name: `${{ parameters.clusterName }}`
          - Atlas UI Name: `${{ parameters.clusterNameInAtlas }}`
          - Environment: `${{ parameters.environment }}`
          - Target Atlas Project (K8s Name): `${{ parameters.atlasProjectNameK8s }}`

          This CRD will be deployed to the `/atlas-crds/` directory.
          The full configuration is also available in its dedicated repository: https://github.com/positive-mental-attitude/${{ parameters.clusterName }}-config.git
        # sourcePath for the PR should point to the specific file in the workspace
        sourcePath: content/${{ parameters.clusterName }}-deployment.yaml
        targetPath: atlas-crds/${{ parameters.clusterName }}-deployment.yaml # Where this file should go in the PR to templates-repo

  output:
    links:
      - title: View New Config Repository
        url: https://github.com/positive-mental-attitude/${{ parameters.clusterName }}-config
      - title: View Pull Request
        url: ${{ steps['create-pr-to-argocd-repo'].output.remoteUrl }}
