# /backstage-templates/create-atlas-cluster/template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-mongodb-atlas-cluster
  title: Create MongoDB Atlas Cluster
  description: Provisions a new MongoDB Atlas cluster.
spec:
  owner: platform-team@example.com
  type: service
  parameters:
    - title: Cluster Configuration
      required:
        - clusterName
        - atlasProjectNameK8s
        - clusterNameInAtlas
        - environment
        - providerName
        - regionName
        - instanceSizeName
      properties:
        clusterName:
          title: Kubernetes Cluster CR Name
          type: string
          description: Unique name for the AtlasDeployment Kubernetes resource (e.g., my-app-user-db).
        atlasProjectNameK8s:
          title: Target AtlasProject Kubernetes Name
          type: string
          description: The 'metadata.name' of the AtlasProject CR to deploy this cluster into (e.g., my-atlas-project-k8s).
        clusterNameInAtlas:
          title: Cluster Name in Atlas UI
          type: string
          description: The name that will appear for this cluster in the MongoDB Atlas UI.
        environment:
          title: Environment
          type: string
          default: development
          enum:
            - development
            - staging
            - production
        providerName:
          title: Cloud Provider
          type: string
          enum: [AWS, GCP, AZURE]
          default: GCP
        regionName:
          title: Region
          type: string
          default: US_EAST_1
        instanceSizeName:
          title: Instance Size
          type: string
          default: M10

  steps:
    - id: fetch-and-template
      name: Fetch Skeleton and Template CRD
      action: fetch:template
      input:
        url: ../atlas-deployment-skeleton.yaml # Path to the skeleton file, relative to this template.yaml
        targetPath: ${{ parameters.clusterName }}.yaml # Output file name in the root of the workspace
        values:
          clusterName: ${{ parameters.clusterName }}
          atlasProjectNameK8s: ${{ parameters.atlasProjectNameK8s }}
          clusterNameInAtlas: ${{ parameters.clusterNameInAtlas }}
          environment: ${{ parameters.environment }}
          providerName: ${{ parameters.providerName }}
          regionName: ${{ parameters.regionName }}
          instanceSizeName: ${{ parameters.instanceSizeName }}
          user: ${{ user }} # Make sure user context is available if used in skeleton

    - id: publish-to-github
      name: Publish CRD to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'Publishing AtlasDeployment CRD for ${{ parameters.clusterName }}'
        repoUrl: 'https://github.com/positive-mental-attitude/templates-repo.git'
        branch: main
        filePath: atlas-crds/${{ parameters.clusterName }}.yaml 
        sourcePath: ${{ parameters.clusterName }}.yaml 
        commitMessage: 'feat: Add AtlasDeployment CRD for ${{ parameters.clusterName }} via Backstage'
        repoVisibility: 'public' 
  output:
    links:
      - title: View CRD in Repository
        url: https://github.com/positive-mental-attitude/templates-repo/blob/main/atlas-crds/${{ parameters.clusterName }}.yaml
